---
- name: Update cache...
  become: yes
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Installing dependencies of elastalert
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - libffi-dev
    - libssl-dev

- name: Installing setuptools 11.3 module using pip3
  become: yes
  pip:
    name:
      - setuptools>=11.3
    executable: pip3
  when: ansible_distribution_version == "18.04"

- name: Installing setuptools with dependencies using pip3
  become: yes
  pip:
    name:
      - "{{ item }}"
    executable: pip3
  with_items:
    - TheHive4py
    - mock
    - configparser
    - setuptools
  when: ansible_distribution_version == "16.04"

- name: Installing PyYAML dependency
  become: yes
  command: "pip3 install -U PyYAML"
  changed_when: true
  args:
    executable: /bin/bash

- name: "Unarchiving elastalert {{ elastalert_version }}"
  become: yes
  unarchive:
    src: "https://github.com/Yelp/elastalert/archive/v{{ elastalert_version }}.tar.gz"
    dest: "{{ installation_dir }}"
    remote_src: true
    creates: "{{ installation_dir }}/elastalert-{{ elastalert_version }}/setup.py"
  register: task_result
  until: task_result is succeeded
  retries: 5
  delay: 5

- name: Creating system group for elastalert
  become: yes
  group:
    name: "{{ elastalert_service_group_name }}"
    state: present

- name: Creating system user for elastalert
  become: yes
  user:
    name: "{{ elastalert_service_user_name }}"
    group: "{{ elastalert_service_group_name }}"
    system: true
    state: present

- name: Symlinking elastalert downloaded directory for ease of use
  become: yes
  file:
    src: "{{ installation_dir }}/elastalert-{{ elastalert_version }}/"
    dest: "{{ installation_dir }}/elastalert"
    owner: "{{ elastalert_service_user_name }}"
    group: "{{ elastalert_service_group_name }}"
    state: link

- name: Setting ownership of elastalert configuration directory
  become: yes
  file:
    path: "{{ elastalert_data_dir }}"
    state: directory
    recurse: true
    owner: "{{ elastalert_service_user_name }}"
    group: "{{ elastalert_service_group_name }}"

- name: Install setuptools 20.10.1 module using pip3
  become: yes
  pip:
    name:
      - setuptools>=20.10.1
    executable: pip3
  when: ansible_distribution_version == "16.04"

- name: Installation of elastalert
  become: yes
  command: "python3 /opt/elastalert/setup.py install"
  changed_when: true

- name: Installation modules from local path
  become: yes
  command: "pip3 install -e /opt/elastalert/."
  changed_when: true
  args:
    executable: /bin/bash

- name: Make sure directory for rules exists
  file:
    path: "{{ elastalert_rules_dir }}"
    state: directory
    owner: "{{ elastalert_service_user_name }}"
    group: "{{ elastalert_service_group_name }}"

- name: get local rules
  delegate_to: localhost
  shell: "ls {{ elastalert_upload_local_rules_dir }}"
  changed_when: false
  register: elastalert_local_rules
  when:
    - elastalert_upload_local_rules_dir != False
  tags: elastalert-rules

- name: get loaded rules
  shell: "ls {{ elastalert_rules_dir }}"
  changed_when: false
  register: elastalert_loaded_rules
  when:
    - elastalert_upload_local_rules_dir != False
  tags: elastalert-rules

- debug:
    var: elastalert_local_rules
  tags: always

- debug:
    var: elastalert_loaded_rules
  tags: always

- name: remove old rules
  become: yes
  file:
    path: "{{elastalert_rules_dir}}/{{ item }}"
    state: absent
  with_items: "{{elastalert_loaded_rules.stdout_lines}}"
  notify:
    - restart elastalert
  when:
    - item not in elastalert_local_rules.stdout_lines | default([])
    - elastalert_delete_rules_not_in_elastalert_upload_local_rules_dir|bool
    - elastalert_upload_local_rules_dir != False
  tags:
    - elastalert-rules

- name: Copying rules into elastalert rules directory
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ elastalert_rules_dir }}"
  with_fileglob:
    - "{{ elastalert_upload_local_rules_dir }}/*"
  when:
    - elastalert_upload_local_rules_dir != False
  notify:
    - restart elastalert
  tags: elastalert-rules
...
