---
- name: elastalert systemd template
  become: yes
  template:
     src: elastalert-systemd.service.j2
     dest: /etc/systemd/system/elastalert.service
     owner: "{{ elastalert_service_user_name }}"
     mode: 0755

- name: get service facts
  service_facts:

- name: config template
  become: yes
  template:
     src: config.yaml.j2
     dest: /opt/elastalert/config.yaml
     backup: yes
  notify:
     - restart elastalert

- name: Setting up Elasticsearch
  command: elastalert-create-index --config /opt/elastalert/config.yaml
  changed_when: true

- name: Make sure Elastalert is started
  service:
    name: elastalert
    state: started
